### ISSUE TITLE
Question about X-DFE-Encoded-Targets

### ISSUE THREAD

**Issue by yotamgod** [MCMrARM/Google-Play-API#20]
Hello,
I really enjoyed this project, and was just wondering about this header.
I've noticed I can still query the api without it, however there are some apps that I cannot find in "details" requests without it.
Is there some explanation for what it is/how it is generated?
Thanks for the project!

**Comment by MCMrARM** [comment]
It's a list of supported experiments, where experiments mean feature toggles (so Google can A/B test some stuff, for example a new design, or a new service, or a new feature). I'm pretty sure you can get list of most of the supported experiments along with their names if you decompile the Google Play Store (at least you used to be able to).

If I had to guess why it fails, it's probably because Google made some of the experiments mandatory to display the details page. Another guess is that they might have broken the details page when an experiment is missing due to an internal server error.
